#!/usr/bin/env node
import { existsSync, readFileSync, readdirSync } from "node:fs";
import { execFileSync } from "node:child_process";
import {
  AGENT_PATHS,
  SKILL_PATHS,
  auditCollisions,
  strayPaths,
} from "./lib/discovery.mjs";
import { parseModelCatalog, pinnedModels } from "./lib/devin-models.mjs";

let problems = 0;
const report = (ok, msg) => {
  console.log(`${ok ? "  ok  " : " FAIL "} ${msg}`);
  if (!ok) problems++;
};

// A tool reading two directories is normal — the ecosystem's convention is one
// real copy under a neutral path, symlinked into each tool's own directory.
// What is never normal is one NAME resolving to two different definitions:
// nothing merges them, one wins, and which one is not something you control.
function auditSection(label, kind, matrix) {
  console.log(`\n${label}`);
  const results = auditCollisions(matrix);
  if (!results.length) {
    console.log(`  info no ${kind} directory present`);
  }
  for (const { tool, sources, count, collisions } of results) {
    if (!collisions.length) {
      console.log(
        `  ok   ${tool}: ${count} ${count === 1 ? kind : `${kind}s`}, ` +
          `no duplicate names (${sources.join(", ")})`,
      );
      continue;
    }
    for (const { name, paths } of collisions) {
      report(false, `${tool}: ${kind} "${name}" resolves to ${paths.length} definitions`);
      for (const p of paths) console.log(`         ${p}`);
    }
    console.log(
      "         → keep one. Delete the redundant copy, or replace it with a\n" +
        "           symlink to the other so both paths resolve to one definition.\n" +
        "           A path listed in config/.agents-manifest.json is generated by\n" +
        "           this roster and is the canonical one.",
    );
  }

  for (const { path, meant } of strayPaths(matrix)) {
    report(false, `${path}/ is read by no tool — a dropped leading dot for ${meant}/`);
    console.log(
      `         → nothing discovers ${path}/, so a definition parked there is an\n` +
        "           invisible second copy. Move it or delete it.",
    );
  }
}

console.log("Agent roster doctor\n==============");

auditSection("Agent definition discovery", "agent", AGENT_PATHS);
auditSection("Skill discovery", "skill", SKILL_PATHS);

console.log("\nMCP sources");
const MCP_SOURCES = {
  claude:      { path: ".mcp.json",              note: "project scope, generated" },
  antigravity: { path: ".agent/mcp_config.json", note: "customization root" },
  devin:       { path: null,                     note: "global only — edit ~/.config/devin/mcp_config.json by hand" },
  codex:       { path: null,                     note: "per-agent `mcp_servers` in .codex/agents/*.toml, or global ~/.codex/config.toml" },
  cursor:      { path: null,                     note: "unverified" },
};
// Informational only — a project may legitimately have no per-tool MCP file
// yet, so these never touch `problems` / the exit code.
for (const [tool, { path, note }] of Object.entries(MCP_SOURCES)) {
  if (!path) console.log(`  info ${tool}: ${note}`);
  else if (existsSync(path)) console.log(`  ok   ${tool}: ${path} (${note})`);
  else console.log(`  warn ${tool}: ${path} missing (${note})`);
}

// Global skill installs, one per harness — not vendored into this repo, so
// existence can only be checked against markers verified on a real machine.
// Each tool below installs superpowers through a different mechanism, and
// each marker was confirmed against this machine on 2026-08-29:
//   Claude Code  — a plugin entry, ~/.claude/plugins/installed_plugins.json
//   Codex        — a plugin entry, ~/.codex/config.toml
//   Antigravity  — a declared skills path, ~/.gemini/config/skills.json
//   Devin        — account-level "personal plugins", installed cloud-side.
//                   There is no local file to check; report how to check it
//                   instead of guessing "absent" for something installed.
console.log("\nGlobal skills (installed per harness, not vendored here)");
const HOME = process.env.HOME ?? "";

const claudePlugins = `${HOME}/.claude/plugins/installed_plugins.json`;
const claudeFound = existsSync(claudePlugins) &&
  readFileSync(claudePlugins, "utf8").includes("superpowers@");
console.log(`  ${claudeFound ? "found  " : "absent "} superpowers — Claude Code (${claudePlugins})`);

const codexConfig = `${HOME}/.codex/config.toml`;
const codexFound = existsSync(codexConfig) &&
  readFileSync(codexConfig, "utf8").includes('[plugins."superpowers@claude-plugins-official"]');
console.log(`  ${codexFound ? "found  " : "absent "} superpowers — Codex (${codexConfig})`);

const geminiSkills = `${HOME}/.gemini/config/skills.json`;
let antigravityFound = false;
if (existsSync(geminiSkills)) {
  const raw = readFileSync(geminiSkills, "utf8");
  antigravityFound = [...raw.matchAll(/"path"\s*:\s*"([^"]*)"/g)]
    .some(([, p]) => p.includes("superpowers"));
}
console.log(`  ${antigravityFound ? "found  " : "absent "} superpowers — Antigravity (${geminiSkills})`);

console.log(
  "  info    superpowers — Devin: personal plugins are account-level and cloud-side, " +
    "no local marker exists; run `devin plugins list` to check",
);
console.log(
  "  info    superpowers:subagent-driven-development and superpowers:executing-plans are\n" +
    "          superseded by this contract — see `### The superpowers boundary` in AGENTS.md",
);

console.log("\nContract reachability");
report(existsSync("AGENTS.md"), "AGENTS.md present (Devin, Antigravity, Cursor, Codex)");
report(existsSync("CLAUDE.md"), "CLAUDE.md present (Claude Code does not read AGENTS.md)");
report(existsSync("GEMINI.md"), "GEMINI.md present (Antigravity)");
report(
  existsSync(".cursor/rules/agent-roster.mdc"),
  ".cursor/rules/agent-roster.mdc present (Cursor)",
);

console.log("\nRepository preconditions");
let hasGit = false;
try {
  execFileSync("git", ["rev-parse", "--git-dir"], { stdio: "pipe" });
  hasGit = true;
} catch {}
report(hasGit, "git repository (the review loop is built on `git diff`)");

// The ledger is the loop's recovery artifact, so it has to be reachable by the
// worker that resumes. Gemini-based harnesses honour .gitignore during file
// discovery (`context.fileFiltering.respectGitIgnore` defaults to true), which
// makes an ignored ledger invisible to Antigravity — and an ignored file does
// not survive a fresh clone or worktree either, which is exactly when the
// recovery artifact is needed.
console.log("\nLedger");
if (hasGit) {
  const ignored = (path) => {
    try {
      execFileSync("git", ["check-ignore", "-q", "--", path], { stdio: "pipe" });
      return true;
    } catch {
      return false;
    }
  };
  const active = existsSync(".roster/ledger.md");
  // Say what is true. `git check-ignore` answers for a path whether or not the
  // file is there, so "is tracked" would be a claim about a file that may not
  // exist — and a doctor that overstates one check is a doctor you stop reading.
  report(
    !ignored(".roster/ledger.md"),
    ignored(".roster/ledger.md")
      ? ".roster/ledger.md is git-ignored — it must be tracked (ignore .roster/review/ instead)"
      : active
        ? ".roster/ledger.md is tracked (survives a reset, visible to Gemini-based harnesses)"
        : "no active ledger, and .roster/ledger.md is not ignored — the next one will be tracked",
  );
  if (!ignored(".roster/review/")) {
    console.log("  warn .roster/review/ is not ignored — captured diffs are scratch, not source");
  }
  if (active) {
    console.log(
      "  info an active ledger is present — a new change archives it first, never overwrites it",
    );
  }
}

console.log("\nWorkspace trust");
function checkAntigravityTrust() {
  const p = `${HOME}/.gemini/trustedFolders.json`;
  if (!existsSync(p)) return { checked: false };
  try {
    const data = JSON.parse(readFileSync(p, "utf8"));
    let curr = process.cwd().toLowerCase();
    while (curr && curr !== "/") {
      const status = data[curr];
      if (status === "TRUST_PARENT" || status === "TRUST" || status === true) {
        return { checked: true, trusted: true, matched: curr };
      }
      const parent = curr.split("/").slice(0, -1).join("/") || "/";
      if (parent === curr) break;
      curr = parent;
    }
    return { checked: true, trusted: false };
  } catch {
    return { checked: false };
  }
}

const agyTrust = checkAntigravityTrust();
if (agyTrust.checked) {
  if (agyTrust.trusted) {
    console.log(`  ok   antigravity: workspace is trusted in ~/.gemini/trustedFolders.json (${agyTrust.matched})`);
  } else {
    console.log(`  warn antigravity: workspace is not in ~/.gemini/trustedFolders.json`);
    console.log(`       (run 'agy' interactively or add '${process.cwd().toLowerCase()}' to trustedFolders.json for background/non-interactive subagents)`);
  }
}

// Devin's own diagnosis of the profiles this roster generated. This is the
// check that would have caught an ignored frontmatter key on day one.
console.log("\nDevin profiles and models");
let devinCli = true;
try {
  execFileSync("command", ["-v", "devin"], { stdio: "pipe", shell: true });
} catch {
  devinCli = false;
}

if (!devinCli) {
  console.log("  info devin CLI absent — skipping profile and model checks");
} else {
  let doctorOut = "";
  try {
    doctorOut = execFileSync("devin", ["doctor"], { encoding: "utf8", stdio: "pipe" });
  } catch (e) {
    doctorOut = e.stdout ?? "";
  }
  for (const line of doctorOut.split("\n")) {
    // Only a FAIL is this repository's problem. `devin doctor` also warns about
    // things this roster does not own, and a warn that fails the run would make
    // `doctor:agents` red for somebody else's stale config. Surface it without
    // failing, exactly as the antigravity trust check above does.
    if (/^\s*fail\b/i.test(line)) report(false, `devin doctor: ${line.trim()}`);
    else if (/^\s*warn\b/i.test(line)) console.log(`  warn devin doctor: ${line.trim()}`);
  }
  const loaded = doctorOut.match(/(\d+) profile\(s\) loaded/);
  if (loaded) console.log(`  ok   devin doctor: ${loaded[1]} subagent profile(s) loaded`);

  const config = JSON.parse(readFileSync("config/agents.json", "utf8"));
  const pins = pinnedModels(config).filter((p) => p.tool === "devin");
  let catalog;
  let modelsFailed = false;
  try {
    catalog = parseModelCatalog(
      execFileSync("devin", ["models", "list"], { encoding: "utf8", stdio: "pipe" }),
    );
  } catch (e) {
    // `devin models list` can fail two ways, and both must collapse to one
    // honest failure line rather than a wall of false per-pin findings:
    //   1. execFileSync throws — command missing, non-zero exit, etc.
    //   2. The command exits 0 but prints an error body instead of a
    //      catalogue — observed when the Devin free-tier quota is exhausted.
    //      The body has no bracketed model rows, so parseModelCatalog returns
    //      an empty Map, which is truthy. Guarding on `catalog` alone would
    //      let the per-model loop run and report every pinned model as one
    //      the command "does not offer" — four FAIL lines for one failure.
    // An empty Map is the same signal as a thrown error: say so once and
    // skip the per-model loop rather than inventing findings.
    modelsFailed = true;
    report(false, `devin models list failed: ${e.message}`);
  }
  if (!modelsFailed && catalog.size === 0) {
    modelsFailed = true;
    report(
      false,
      "devin models list returned no models (exited 0 with an empty catalogue — likely a quota or connection error)",
    );
  }
  for (const { where, model } of modelsFailed ? [] : pins) {
    const entry = catalog.get(model);
    if (!entry) {
      report(false, `devin: ${where} pins model "${model}", which devin models list does not offer`);
    } else if (!entry.free) {
      console.log(`  warn devin: ${where} pins "${model}" (${entry.label}) — no longer free`);
    } else {
      console.log(`  ok   devin: ${where} → ${model} (${entry.label}, free)`);
    }
  }
}

console.log("\nInstalled CLIs");
for (const [bin, name] of [
  ["claude", "Claude Code"], ["devin", "Devin"],
  ["agy", "Antigravity"], ["cursor-agent", "Cursor"], ["codex", "Codex"],
]) {
  let found = false;
  try {
    execFileSync("command", ["-v", bin], { stdio: "pipe", shell: true });
    found = true;
  } catch {}
  console.log(`  ${found ? "found  " : "absent "} ${name} (${bin})`);
}

// Read the role list rather than naming roles here. A hardcoded list is the
// copy nobody updates, and this footer is the one place a human is told what
// "correct" looks like.
const roleNames = existsSync("agents/roles")
  ? readdirSync("agents/roles", { withFileTypes: true })
      .filter((e) => e.isDirectory())
      .map((e) => e.name)
      .sort()
  : [];

console.log(`
Manual discovery checks — run each in the tool itself and confirm you see
exactly ONE of each of these ${roleNames.length} roles, and no duplicates:

  ${roleNames.join(", ")}

  Claude Code   /agents
  Devin         /agents        (also confirm no duplicates from .agent/ or .claude/)
  Antigravity   /agents        (CLI) or the agent picker (IDE)
  Cursor        type /  in the composer and look for the names
  Codex         /agent
`);

process.exit(problems ? 1 : 0);
